# Site settings
title: Mihail Eric
author: Mihail Eric
email: mihail911@gmail.com  
description: Fun times
baseurl: "" # optional
url: "www.mihaileric.com"
twitter_username: mihail_eric
github_username: mihail911
#github_repo: foo_bar/foo_bar.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
